name: Static Scan

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:

jobs:
  analyze:
    # https://github.com/github/codeql-action
    name: Static Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          config-file: ./.github/codeql/codeql-config.yml

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      # - name: Run Codacy Analysis CLI
      #   uses: codacy/codacy-analysis-cli-action@master
      #   with:
      #     output: results.sarif
      #     format: sarif
      #     gh-code-scanning-compat: true
      #     max-allowed-issues: 2147483647

      # - name: Upload SARIF results file
      #   uses: github/codeql-action/upload-sarif@main
      #   with:
      #     sarif_file: results.sarif

      - name: Check License Lines
        uses: kt3k/license_checker@master

      - name: Run PSRule analysis
        uses: Microsoft/ps-rule@main
        with:
          modules: PSRule.Rules.GitHub, PSRule.Rules.MSFT.OSS
          prerelease: true
